description "Deuteriumcoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env DEUTERIUMCOIND_BIN="/usr/bin/deuteriumcoind"
env DEUTERIUMCOIND_USER="deuteriumcoin"
env DEUTERIUMCOIND_GROUP="deuteriumcoin"
env DEUTERIUMCOIND_PIDDIR="/var/run/deuteriumcoind"
# upstart can't handle variables constructed with other variables
env DEUTERIUMCOIND_PIDFILE="/var/run/deuteriumcoind/deuteriumcoind.pid"
env DEUTERIUMCOIND_CONFIGFILE="/etc/deuteriumcoin/deuteriumcoin.conf"
env DEUTERIUMCOIND_DATADIR="/var/lib/deuteriumcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # deuteriumcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$DEUTERIUMCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run deuteriumcoind."
        echo "The setting must appear in $DEUTERIUMCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Deuteriumcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$DEUTERIUMCOIND_PIDDIR"
    chmod 0755 "$DEUTERIUMCOIND_PIDDIR"
    chown $DEUTERIUMCOIND_USER:$DEUTERIUMCOIND_GROUP "$DEUTERIUMCOIND_PIDDIR"
    chown $DEUTERIUMCOIND_USER:$DEUTERIUMCOIND_GROUP "$DEUTERIUMCOIND_CONFIGFILE"
    chmod 0660 "$DEUTERIUMCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$DEUTERIUMCOIND_PIDFILE" \
    --chuid $DEUTERIUMCOIND_USER:$DEUTERIUMCOIND_GROUP \
    --exec "$DEUTERIUMCOIND_BIN" \
    -- \
    -pid="$DEUTERIUMCOIND_PIDFILE" \
    -conf="$DEUTERIUMCOIND_CONFIGFILE" \
    -datadir="$DEUTERIUMCOIND_DATADIR" \
    -disablewallet \
    -daemon

